### ISSUE TITLE
please include a LICENSE file

### ISSUE THREAD

**Issue by decathorpe** [emilk/snake_case#2]
The MIT license(s) require that the license text is included with (redistributed) sources, and for example, the [Fedora](https://fedoraproject.org/wiki/Licensing:MIT) project recognises at least 23 main (!) variants of the MIT license, which can only be distinguished by actually including a license text.

The MIT variant that seems to be most used by Rust projects seems to be the one categorized by Fedora as [Modern Style with sublicense](https://fedoraproject.org/wiki/Licensing:MIT#Modern_Style_with_sublicense), which contains the same text as the MIT license examples on [choosealicense.com](https://choosealicense.com/licenses/mit/) and [opensource.org](https://opensource.org/licenses/MIT).

Please also amend the `include` field in `Cargo.toml` to include this LICENSE file, as well, so that this file is also included in crates that are published to crates.io. Thanks!

**Comment by emilk** [comment]
Good call - thank you!
